"""add_tables

Revision ID: 24104b6e1e0c
Revises: a8483365f505
Create Date: 2021-06-20 08:28:35.834586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "24104b6e1e0c"
down_revision = "a8483365f505"
branch_labels = None
depends_on = None


def upgrade():
    # Preprocess
    pre_upgrade()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notebooks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notebooks")),
        sa.UniqueConstraint("id", name=op.f("uq_notebooks_id")),
    )
    op.create_table(
        "notes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=64), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("notebook_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["notebook_id"], ["notebooks.id"], name=op.f("fk_notes_notebook_id_notebooks")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notes")),
        sa.UniqueConstraint("id", name=op.f("uq_notes_id")),
    )
    # ### end Alembic commands ###

    # Postprocess
    post_upgrade()


def downgrade():
    # Preprocess
    pre_downgrade()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notes")
    op.drop_table("notebooks")
    # ### end Alembic commands ###

    # Postprocess
    post_downgrade()


def pre_upgrade():
    # Processing before upgrading the schema
    pass


def post_upgrade():
    # Processing after upgrading the schema
    pass


def pre_downgrade():
    # Processing before downgrading the schema
    pass


def post_downgrade():
    # Processing after downgrading the schema
    pass
